apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo-react-website
  annotations:
    github.com/project-slug: "external-spotify-portal-demo/demo-react-website"
spec:
  type: website
  lifecycle: experimental
  owner: belugas
