apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo-workflows
  annotations:
    github.com/project-slug: "external-spotify-portal-demo/demo-workflows"
spec:
  type: website
  lifecycle: experimental
  owner: kubecon-squad
